### ISSUE TITLE
Can you please explain to me how this program works with end user?

### ISSUE THREAD

**Issue by photoboothbiz** [pgmrgeek/PhotoboothMgr#1]
I have downloaded this program and followed the setup instructions meticulously, but I do not understand how it is supposed to work. Here are my questions sorry for so many.
#1. will this program only work with the sony 150 and DS40? Or perhaps only those two print resolutions are supported 334ppi and 300ppi?
#2. When people are in the booth, what are they seeing on a monitor or doing? I assume they are using a program like canon utility to manually take one photo at a time? I guess it could be any program even a webcamera one?
#3. I do not understand the way the program prints? I have loaded the default green screen and other pics and I have loaded 3 or them and nothing happens.

are you aware that you can get canon sdk files easily directly from canon?
http://www.codeproject.com/Articles/688276/Canon-EDSDK-Tutorial-in-Csharp

this web site gives basic information on how to control the camera with canon SDK, it should save any programmer hours of time since most basic operations are already spelled out.

thanks for reading my comments and happy holidays
If I can get this program to work I will make a donation and some youtube tutorials on how it works so more people can understand and use it. I really like the idea of having powerfull image editor running a booth. 

info@photo-booth.biz

**Comment by pgmrgeek** [comment]
Hi,

For answers see below..

..Doug

---

On Sat, 12/20/14, photoboothbiz notifications@github.com wrote:

 Subject: [PhotoboothMgr] Can you please explain to me how this program works with end user? (#1)
 To: "pgmrgeek/PhotoboothMgr" PhotoboothMgr@noreply.github.com
 Date: Saturday, December 20, 2014, 7:42 AM

 I have downloaded this program
 and followed the setup instructions meticulously, but I do
 not understand how it is supposed to work. Here are my
 questions sorry for so many.

 #1.
 will this program only work with the sony 150 and DS40? Or
 perhaps only those two print resolutions are supported
 334ppi and 300ppi?

The printers are listed in the printers.csv file.  These can easily be changed out for other printers.  What printers do you use?
I'll edit a file and send it to you.

 #2. When people are in the booth, what are they seeing on a
 monitor or doing? I assume they are using a program like
 canon utility to manually take one photo at a time? I guess
 it could be any program even a web camera one?

people in the booths seeing themselves is separate from this program. if you want a monitor for the people to see, 
I would suggest using the HDMI output on the camera attached to a monitor so the guests could see themselves. 
I've tried  Liveview through the canon software with a display window on a monitor, but that shuts down the hotshoe 
on the camera, disabling the strobes.  May not be a problem if you have other means to light the area.  
Future canon cameras will allow the hotshoe to work when running in liveview.  

I use the canon EOS utility to tether a camera to the computer.  That software delivers .jpgs to the c:\onsite\capture 
folder to be processed by the operator.  Images that land in the c:\onsite folder will automatically be processed in "kiosk 
mode" without operator intervention.

 #3. I do not understand the way the program prints? I have
 loaded the default green screen and other pics and I have
 loaded 3 or them and nothing happens.

If you see the three images on the Pic2Print main panel, you have loaded them in the "c:\onsite\capture" folder. Click
on an image, then click a number 1 - 10 below the image.  Thats the number of prints to be printed.  The program will
pass that information to photoshop along with the layout you've selected in the setup config panel.

Did you look over the setup configuration panel?  This allows you to select printer sizes and layouts.  Below the
layouts are additional features.  The layout you select will determine some of these features (The checkboxes
automatically change).  You can override the features by manually changing the checkboxes after selecting one
of the layouts.

 are you aware that you can get canon sdk files easily
 directly from canon?

 http://www.codeproject.com/Articles/688276/Canon-EDSDK-Tutorial-in-Csharp

 this web site gives basic information on how to control
 the camera with canon SDK, it should save any programmer
 hours of time since most basic operations are already
 spelled out.

 thanks for reading my comments and happy holidays

 If I can get this program to work I will make a donation and
 some youtube tutorials on how it works so more people can
 understand and use it. I really like the idea of having
 powerfull image editor running a booth. 

 info@photo-booth.biz

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by photoboothbiz** [comment]
thanks again for making this software.

  so If I understand you correctly there is no countdown and autmatically shooting of four images? how are the images trigger in your set up? controlled manually by operator I assume?
  I think this type of program is more accurately called a hot folder printer program? might help people better understand it becuase the name implies an phtobooth type functinality.

  Maybe I just don't know where to look but I can't find the kiosk mode button?

  thanks again for the help.

  Sincerely, Elliott  www.photo-booth.biz

   On December 22, 2014 at 10:01 AM Doug Cody notifications@github.com wrote:

   Hi, 

```
For answers see below.. 

..Doug 

-------------------------------------------- 
On Sat, 12/20/14, photoboothbiz <notifications@github.com> wrote: 

Subject: [PhotoboothMgr] Can you please explain to me how this program works with end user? (#1) 
To: "pgmrgeek/PhotoboothMgr" <PhotoboothMgr@noreply.github.com> 
Date: Saturday, December 20, 2014, 7:42 AM 

I have downloaded this program     and followed the setup instructions meticulously, but I do 
not understand how it is supposed to work. Here are my  questions sorry for so many. 

#1. 
will this program only work with the sony 150 and DS40? Or  perhaps only those two print 
```

   resolutions are supported 334ppi and 300ppi? 

   Answer: The printers are listed in the printers.csv file. These can easily be changed out for
   other printers. What printers do you use?   I'll edit a file and send it to you. 

```
#2. When people are in the booth, what are they seeing on a monitor or doing? I assume they 
are using a program like canon utility to manually take one photo at a time? I guess 
it could be any program even a web camera one? 

Answer: People in the booths seeing themselves is separate from this program. if you want 
a monitor for the people to see, I would suggest using the HDMI output on the camera attached
to a monitor so the guests could see themselves. I've tried Liveview through the canon software 
with a display window on a monitor, but that shuts down the hotshoe on the camera, disabling
the strobes. May not be a problem if you have other means to light the area.  Future canon 
cameras will allow the hotshoe to work when running in liveview. 

I use the canon EOS utility to tether a camera to the computer. That software delivers .jpgs to 
the c:\onsite\capture folder to be processed by the operator. Images that land in the c:\onsite 
folder will automatically be processed in "kiosk mode" without operator intervention. 

#3. I do not understand the way the program prints? I have loaded the default green screen and 
other pics and I have loaded 3 or them and nothing happens. 

If you see the three images on the Pic2Print main panel, you have loaded them in the 
"c:\onsite\capture" folder. Click on an image, then click a number 1 - 10 below the image. 
 Thats the number of prints to be printed. The program will pass that information to photoshop 
 along with the layout you've selected in the setup config panel. 

Did you look over the setup configuration panel? This allows you to select printer sizes and layouts. 
Below the layouts are additional features. The layout you select will determine some of these 
features (The checkboxes automatically change). You can override the features by manually 
changing the checkboxes after selecting one of the layouts. 

are you aware that you can get canon sdk files easily directly from canon? 
http://www.codeproject.com/Articles/688276/Canon-EDSDK-Tutorial-in-Csharp 

this web site gives basic information on how to control the camera with canon SDK, it should save 
any programmer hours of time since most basic operations are already spelled out. 

thanks for reading my comments and happy holidays 

If I can get this program to work I will make a donation and some youtube tutorials on how it 
works so more people can understand and use it. I really like the idea of having powerfull image 
editor running a booth. 

info@photo-booth.biz 

— 
```

**Comment by pgmrgeek** [comment]
Hi Elliot.

If it would make it easier, give me a call tomorrow at 408.293.3080.  Thats the office #.  I'll be in tomorrow around 9am pst.  Toll free at 877-368-6677.

Kiosk mode always runs; there's no button to turn it on.  Do this.  select layout 000 and copy a jpg to the c:\onsite folder.  It should load and process through photoshop.  Then, go back to the config panel and select the 4 image photo strip.  Copy 4 images to the c:\onsite folder.  The program will process them correctly.  

The c:\onsite\capture folder is really setup for an operator to see and select the images to be processed.  When the operator prints an image, it gets copied into the c:\onsite folder!  Its not quite visible whats happening, but the operator is using the kiosk mode when clicking an image, then print count.  If you just want kiosk mode, then select your layout in the config panel, and copy images to the c:\onsite as your hot folder.

To say it another way, Kiosk mode takes any image in the c:\onsite folder and processes them according to the config panel settings.  If you want a photo strip with 4 photos, select that layout and then look at the check boxes and numbers below the selection.  You will see those options change to work with  a 4 image photo strip.   The program does keep track of that.

One way I run open air photo booths, is to give a wireless transmitter to the guests to let them trigger 4 frames from the camera.  The images land in c:\onsite and automatically print 2 2x6 photo strips (one 4x6 cut into two 2x6 strips).  

Oh, what printers do you use?

..Doug

---

On Mon, 12/22/14, photoboothbiz notifications@github.com wrote:

 Subject: Re: [PhotoboothMgr] Can you please explain to me how this program works with end user? (#1)
 To: "pgmrgeek/PhotoboothMgr" PhotoboothMgr@noreply.github.com
 Cc: "Doug Cody" clikphoto@yahoo.com
 Date: Monday, December 22, 2014, 7:42 AM

   thanks again for making this software.

```
so If I understand you correctly there is no countdown and
```

 autmatically shooting of four images? how are the images
 trigger in your set up? controlled manually by operator I
 assume?

```
I think this type of program is more accurately called a
```

 hot folder printer program? might help people better
 understand it becuase the name implies an phtobooth type
 functinality.

   Maybe I just don't know where to look but I can't
 find the kiosk mode button?

```
thanks again for the help.
```

   Sincerely, Elliott 704 726
 9788www.photo-booth.bizCONFIDENTIALITY NOTICE: The
 information contained in this message is privileged and
 confidential, and may be protected from disclosure. If the
 reader of this message is not the intended recipient, or any
 employee or agent responsible for delivering this message to
 the intended recipient, you are hereby notified that any
 dissemination, distribution, or copying of this
 communication is strictly prohibited. If you have received
 this communication in error, please notify us immediately by
 replying to the message and delete it (and any attachments)
 from your computer.CONDITIONS OF SALE VIA EMAIL
 COMMUNICATION: By communication via email buyer agrees to
 sellers return, fabrication, and selling policies listed on
 the website photo-booth.biz

```
On December 22, 2014 at 10:01 AM Doug Cody
```

 notifications@github.com wrote:

```
Hi, 





 For answers see below.. 





 ..Doug 





 -------------------------------------------- 


 On Sat, 12/20/14, photoboothbiz
```

 notifications@github.com wrote: 

```
 Subject: [PhotoboothMgr] Can you please explain to me
```

 how this program works with end user? (#1) 

```
 To: "pgmrgeek/PhotoboothMgr"
```

 PhotoboothMgr@noreply.github.com 

```
 Date: Saturday, December 20, 2014, 7:42 AM 





 I have downloaded this program 


 and followed the setup instructions meticulously, but I
```

 do 

```
 not understand how it is supposed to work. Here are my 


 questions sorry for so many. 





 #1. 


 will this program only work with the sony 150 and DS40?
```

 Or 

```
 perhaps only those two print resolutions are supported 


 334ppi and 300ppi? 





 The printers are listed in the printers.csv file. These
```

 can easily be changed out for other printers. What printers
 do you use? 

```
 I'll edit a file and send it to you. 





 #2. When people are in the booth, what are they seeing
```

 on a 

```
 monitor or doing? I assume they are using a program like



 canon utility to manually take one photo at a time? I
```

 guess 

```
 it could be any program even a web camera one? 





 people in the booths seeing themselves is separate from
```

 this program. if you want a monitor for the people to see, 

```
 I would suggest using the HDMI output on the camera
```

 attached to a monitor so the guests could see themselves. 

```
 I've tried Liveview through the canon software with
```

 a display window on a monitor, but that shuts down the
 hotshoe 

```
 on the camera, disabling the strobes. May not be a
```

 problem if you have other means to light the area. 

```
 Future canon cameras will allow the hotshoe to work when
```

 running in liveview. 

```
 I use the canon EOS utility to tether a camera to the
```

 computer. That software delivers .jpgs to the
 c:\onsite\capture 

```
 folder to be processed by the operator. Images that land
```

 in the c:\onsite folder will automatically be processed
 in "kiosk 

```
 mode" without operator intervention. 





 #3. I do not understand the way the program prints? I
```

 have 

```
 loaded the default green screen and other pics and I
```

 have 

```
 loaded 3 or them and nothing happens. 





 If you see the three images on the Pic2Print main panel,
```

 you have loaded them in the
 "c:\onsite\capture" folder. Click 

```
 on an image, then click a number 1 - 10 below the image.
```

 Thats the number of prints to be printed. The program will 

```
 pass that information to photoshop along with the layout
```

 you've selected in the setup config panel. 

```
 Did you look over the setup configuration panel? This
```

 allows you to select printer sizes and layouts. Below the 

```
 layouts are additional features. The layout you select
```

 will determine some of these features (The checkboxes 

```
 automatically change). You can override the features by
```

 manually changing the checkboxes after selecting one 

```
 of the layouts. 





 are you aware that you can get canon sdk files easily 


 directly from canon? 
```

 http://www.codeproject.com/Articles/688276/Canon-EDSDK-Tutorial-in-Csharp

```
 this web site gives basic information on how to control 


 the camera with canon SDK, it should save any programmer



 hours of time since most basic operations are already 


 spelled out. 





 thanks for reading my comments and happy holidays 





 If I can get this program to work I will make a donation
```

 and 

```
 some youtube tutorials on how it works so more people
```

 can 

```
 understand and use it. I really like the idea of having 


 powerfull image editor running a booth. 





 info@photo-booth.biz 





 — 


 Reply to this email directly or view 


 it on GitHub. 























—Reply to this email directly or view it on GitHub.
```

    

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by pgmrgeek** [comment]
Hi Elliot,

I have a question for you.  Would you like to see some form of a message to the user, like a number count down and "SAY CHEESE" on a second monitor (assuming that second monitor is in the booth facing the guests?).  Also, having the camera under control using the canon SDK to trigger a frame, doing this for say 4 frames (or whatever the layout specifies)?  I could add that as a prompter form, in addition to the preview and post view forms.

## ..Doug

On Sat, 12/20/14, photoboothbiz notifications@github.com wrote:

 Subject: [PhotoboothMgr] Can you please explain to me how this program works with end user? (#1)
 To: "pgmrgeek/PhotoboothMgr" PhotoboothMgr@noreply.github.com
 Date: Saturday, December 20, 2014, 7:42 AM

 I have downloaded this program and followed the setup instructions meticulously, but I do
 not understand how it is supposed to work. Here are my questions sorry for so many.

 #1.
 will this program only work with the sony 150 and DS40? Or  perhaps only those two print resolutions 
 are supported 334ppi and 300ppi?

 #2. When people are in the booth, what are they seeing on a monitor or doing? I assume they are 
 using a program like canon utility to manually take one photo at a time? I guess  it could be any  
 program even a webcamera one?

 #3. I do not understand the way the program prints? I have loaded the default green screen and 
 other pics and I have loaded 3 or them and nothing happens.

 are you aware that you can get canon sdk files easily directly from canon?

 http://www.codeproject.com/Articles/688276/Canon-EDSDK-Tutorial-in-Csharp

 this web site gives basic information on how to control the camera with canon SDK, it should save 
 any programmer hours of time since most basic operations are already  spelled out.

 thanks for reading my comments and happy holidays

 If I can get this program to work I will make a donation and  some youtube tutorials on how it works 
so more people can understand and use it. I really like the idea of having  powerfull image editor 
running a booth. 

 info@photo-booth.biz

 —

**Comment by photoboothbiz** [comment]
I think if it had a customer interface it would make it much more appealing! 

   http://www.codeproject.com/Articles/688276/Canon-EDSDK-Tutorial-in-Csharp

  is the tutorial site I mentioned before for dslr's.

  Also there is this open source program for powershot cameras, maybe you can download the source code and make it work with DSLR's?I actually contacted the creator and offered to pay him but he was not interested at all at any price. 

  http://sourceforge.net/projects/openphotobooth/files/

  i also found this code also for point and shoots.

  http://sourceforge.net/projects/photobooth/files/photobooth/

  I thought about learning C#, but honestly I think it might be too time consuming and after I made the program I'd probably not use the C# language that much and forget it. 

  I'd be glad to pay you as well. This industry really needs some open source code that works. If you are not interested and know of anyone I'd be glad to talk to them as well. Finding a programmer seems to be a hard task! Maybe I am just asking in the wrong places?!?

  Sincerely, Elliott  www.photo-booth.biz

   On December 23, 2014 at 1:01 AM Doug Cody notifications@github.com wrote:

   Hi Elliot, 

```
I have a question for you. Would you like to see some form of a message to the user, like a number count down and "SAY CHEESE" on a second monitor (assuming that second monitor is in the booth facing the guests?). Also, having the camera under control using the canon SDK to trigger a frame, doing this for say 4 frames (or whatever the layout specifies)? I could add that as a prompter form, in addition to the preview and post view forms. 

..Doug 
-------------------------------------------- 
On Sat, 12/20/14, photoboothbiz <notifications@github.com> wrote: 

Subject: [PhotoboothMgr] Can you please explain to me how this program works with end user? (#1) 
To: "pgmrgeek/PhotoboothMgr" <PhotoboothMgr@noreply.github.com> 
Date: Saturday, December 20, 2014, 7:42 AM 

I have downloaded this program     and followed the setup instructions meticulously, but I do 
not understand how it is supposed to work. Here are my  questions sorry for so many. 

#1. 
will this program only work with the sony 150 and DS40? Or perhaps only those two print 
resolutions are supported 334ppi and 300ppi? 

#2. When people are in the booth, what are they seeing on a monitor or doing? I assume they are 
using a program like canon utility to manually take one photo at a time? I guess it could be any 
program even a webcamera one? 

#3. I do not understand the way the program prints? I have loaded the default green screen and 
other pics and I have loaded 3 or them and nothing happens. 

are you aware that you can get canon sdk files easily  directly from canon? 

http://www.codeproject.com/Articles/688276/Canon-EDSDK-Tutorial-in-Csharp 

this web site gives basic information on how to control the camera with canon SDK, it should save 
any programmer hours of time since most basic operations are already spelled out. 

thanks for reading my comments and happy holidays 

If I can get this program to work I will make a donation and some youtube tutorials on how it works 
so more people can understand and use it. I really like the idea of having powerfull image editor 
running a booth. 

info@photo-booth.biz 

— 
```

**Comment by pgmrgeek** [comment]
Hi Elliott,

For the Customer interface, check out the Preview and Post View buttons.  Those open up VB 
forms with images.  I use the Preview form for guests to select their images for printing.  The 
post view shows the printed folder, so it shows what the images look like after processing.  There's 
also a reprint button on that screen.  To operate the preview window, the operator just has to 
click on one of the visible thumbnails on the main window, it appears on the Preview. The Preview 
window can be displayed on a second monitor and can be resized to full screen. I do need
to make the Post View window scalable in that same way.

On the camera interface, that's a separate subject from the customer interface.  Both camera and 
printer drivers must be supplied by their respective hardware manufactures.  As far as I know, each 
camera ships with a CD with this type of capture software from the manufacture.   I use Canon EOS 
Utilities to tether the camera to the computer. The utility is configured to drop the images in either 
c:\onsite\capture for the operator, or c:\onsite for kiosk mode.  Nikon owners can use Nikon Capture 
software to tether their cameras (I setup this for my friends camera once; it worked very well).  Eye-Fi 
cards can drop images on the computer, so that can work too. I used Eye-Fi in the early years to do 
this work.  All these solutions would be impossible to support here.  Each of those third party software
pieces work well with Pic2Print, but don't need to be integrated into the projects here on GitHub 
(copyright issues, etc.) .  I'd rather those manufactures support their own products rather than 
taking on their support issues here.

..Doug

---

On Tue, 12/23/14, photoboothbiz notifications@github.com wrote:

 Subject: Re: [PhotoboothMgr] Can you please explain to me how this program works with end user? (#1)
 To: "pgmrgeek/PhotoboothMgr" PhotoboothMgr@noreply.github.com
 Cc: "Doug Cody" clikphoto@yahoo.com
 Date: Tuesday, December 23, 2014, 6:39 AM

 I think if it had a customer interface it would make it much more appealing! 

 http://www.codeproject.com/Articles/688276/Canon-EDSDK-Tutorial-in-Csharp

 is the tutorial site I mentioned before for dslr's.

Also there is this open source program for powershot cameras, maybe you can download the source 
code and make it work with DSLR's? I actually contacted the creator and offered to pay him but he 
was not interested at all at any price. 

 http://sourceforge.net/projects/openphotobooth/files/

 i also found this code also for point and shoots.

 http://sourceforge.net/projects/photobooth/files/photobooth/

 I thought about learning C#, but honestly I think it might  be too time consuming and after I made 
 the program I'd probably not use the C# language that much  and forget it. 

 I'd be glad to pay you as well. This industry really needs some open source 
 code that works. If you are not  interested and know of anyone I'd be glad to talk to
 them as well. Finding a programmer seems to be a hard task! Maybe I am 
 just asking in the wrong places?!?

 Sincerely, Elliott www.photo-booth.biz

**Comment by photoboothbiz** [comment]
sorry about my phone keeps dropping the call. I need to move the computer and printer from out of my basement to upstairs and get this working.
  Hope you have a merry christmas. 

  Sincerely, Elliott 704 726 9788www.photo-booth.bizCONFIDENTIALITY NOTICE: The information contained in this message is privileged and confidential, and may be protected from disclosure. If the reader of this message is not the intended recipient, or any employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately by replying to the message and delete it (and any attachments) from your computer.CONDITIONS OF SALE VIA EMAIL COMMUNICATION: By communication via email buyer agrees to sellers return, fabrication, and selling policies listed on the website photo-booth.biz

   On December 23, 2014 at 11:02 AM Doug Cody notifications@github.com wrote:

   Hi Elliott, 

```
For the Customer interface, check out the Preview and Post View buttons. Those open up VB forms with images. 
I use the Preview form for guests to select their images for printing. The post view shows the printed folder, so it 
shows what the images look like after processing. There's also a reprint button on that screen. To operate the 
preview window, the operator just has to click on one of the visible thumbnails on the main window, it appears on 
the Preview. The Preview window can be displayed on a second monitor and can be resized to full screen. I do need 
to make the Post View window scalable in that same way. 

On the camera interface, that's a separate subject from the customer interface. Both camera and printer drivers 
must be supplied by their respective hardware manufactures. As far as I know, each camera ships with a CD with 
this type of capture software from the manufacture. I use Canon EOS Utilities to tether the camera to the 
computer. The utility is configured to drop the images in either c:\onsite\capture for the operator, or c:\onsite 
for kiosk mode. Nikon owners can use Nikon Capture software to tether their cameras (I setup this for my friends 
camera once; it worked very well). Eye-Fi cards can drop images on the computer, so that can work too. I used 
Eye-Fi in the early years to do this work. All these solutions would be impossible to support here. Each of those 
third party software pieces work well with Pic2Print, but don't need to be integrated into the projects here on GitHub 
(copyright issues, etc.) . I'd rather those manufactures support their own products rather than taking on their support 
issues here. 

..Doug 

-------------------------------------------- 
On Tue, 12/23/14, photoboothbiz <notifications@github.com> wrote: 

Subject: Re: [PhotoboothMgr] Can you please explain to me how this program works with end user? (#1) 
To: "pgmrgeek/PhotoboothMgr" <PhotoboothMgr@noreply.github.com> 
Cc: "Doug Cody" <clikphoto@yahoo.com> 
Date: Tuesday, December 23, 2014, 6:39 AM 

I think if it had a customer interface it would make it much more appealing! 

http://www.codeproject.com/Articles/688276/Canon-EDSDK-Tutorial-in-Csharp 

is the tutorial site I mentioned before for dslr's. 

Also there is this open source program for powershot cameras, maybe you can download the source 
code and make it work with DSLR's? I actually contacted the creator and offered to pay him but he 
was not interested at all at any price. 

http://sourceforge.net/projects/openphotobooth/files/ 

i also found this code also for point and shoots. 

http://sourceforge.net/projects/photobooth/files/photobooth/ 

I thought about learning C#, but honestly I think it might be too time consuming and after I made 
the program I'd probably not use the C# language that much and forget it. 

I'd be glad to pay you as well. This industry really needs some open source 
code that works. If you are not interested and know of anyone I'd be glad to talk to 
them as well. Finding a programmer seems to be a hard task! Maybe I am 
just asking in the wrong places?!? 

Sincerely, Elliott www.photo-booth.biz
```

**Comment by pgmrgeek** [comment]
Hi Elliott,

Check out version 13.xx.  This is the first version to support DigiCamControl for triggering cameras.  There is a new button, the "Guest UI" button that opens a dialog with one button - "Click to start".  Resize this button over the whole screen so the user has one option, to start the sequence.  There's a little nearly hidden button at the bottom right to minimize this dialog to see the rest of the program and photoshop.  

Let me know if you need assistance getting this up and running.

..Doug

**Comment by photoboothbiz** [comment]
cool this was the last link in the puzzle to make it a full fledged program, great job. I will check it out soon. On July 26, 2016 at 8:11 PM Doug Cody notifications@github.com wrote:Hi Elliott,Check out version 13.xx. This is the first version to support DigiCamControl for triggering cameras. There is a new button, the "Guest UI" button that opens a dialog with one button - "Click to start". Resize this button over the whole screen so the user has one option, to start the sequence. There's a little nearly hidden button at the bottom right to minimize this dialog to see the rest of the program and photoshop.Let me know if you need assistance getting this up and running...Doug—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by pgmrgeek** [comment]
Howdy,
Any luck getting the software to run?  Attached is a spreadsheet which is a checklist at startup (not installation, but on job site..).  I'll add this to the repository but thought I'd pass it by you for feedback.
..Doug

```
  From: photoboothbiz <notifications@github.com>
```

 To: pgmrgeek/PhotoboothMgr PhotoboothMgr@noreply.github.com 
Cc: Doug Cody clikphoto@yahoo.com; State change state_change@noreply.github.com
 Sent: Monday, August 8, 2016 11:03 AM
 Subject: Re: [pgmrgeek/PhotoboothMgr] Can you please explain to me how this program works with end user? (#1)

cool this was the last link in the puzzle to make it a full fledged program, great job. I will check it out soon. On July 26, 2016 at 8:11 PM Doug Cody notifications@github.com wrote:Hi Elliott,Check out version 13.xx. This is the first version to support DigiCamControl for triggering cameras. There is a new button, the "Guest UI" button that opens a dialog with one button - "Click to start". Resize this button over the whole screen so the user has one option, to start the sequence. There's a little nearly hidden button at the bottom right to minimize this dialog to see the rest of the program and photoshop.Let me know if you need assistance getting this up and running...Doug—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. —

**Comment by photoboothbiz** [comment]
SORRY BEEN SWAMPED, REALLY AM INTERESTED THOUGH, YOU ARE VERY VERY GENEROUS WITH YOUR SHARING OF SOFTARE!On August 14, 2016 at 5:26 PM Doug Cody notifications@github.com wrote:Howdy, Any luck getting the software to run?  Attached is a spreadsheet which is a checklist at startup (not installation, but on job site..).  I'll add this to the repository but thought I'd pass it by you for feedback. ..Doug  From: photoboothbiz notifications@github.com To: pgmrgeek/PhotoboothMgr PhotoboothMgr@noreply.github.com  Cc: Doug Cody clikphoto@yahoo.com; State change state_change@noreply.github.com Sent: Monday, August 8, 2016 11:03 AM Subject: Re: [pgmrgeek/PhotoboothMgr] Can you please explain to me how this program works with end user? (#1)    cool this was the last link in the puzzle to make it a full fledged program, great job. I will check it out soon. On July 26, 2016 at 8:11 PM Doug Cody notifications@github.com wrote:Hi Elliott,Check out version 13.xx. This is the first version to support DigiCamControl for triggering cameras. There is a new button, the "Guest UI" button that opens a dialog with one button - "Click to start". Resize this button over the whole screen so the user has one option, to start the sequence. There's a little nearly hidden button at the bottom right to minimize this dialog to see the rest of the program and photoshop.Let me know if you need assistance getting this up and running...Doug—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by pgmrgeek** [comment]
Howdy,
any luck with getting it running?
..Doug

```
  From: photoboothbiz <notifications@github.com>
```

 To: pgmrgeek/PhotoboothMgr PhotoboothMgr@noreply.github.com 
Cc: Doug Cody clikphoto@yahoo.com; State change state_change@noreply.github.com
 Sent: Monday, August 15, 2016 5:09 AM
 Subject: Re: [pgmrgeek/PhotoboothMgr] Can you please explain to me how this program works with end user? (#1)

SORRY BEEN SWAMPED, REALLY AM INTERESTED THOUGH, YOU ARE VERY VERY GENEROUS WITH YOUR SHARING OF SOFTARE!On August 14, 2016 at 5:26 PM Doug Cody notifications@github.com wrote:Howdy, Any luck getting the software to run?  Attached is a spreadsheet which is a checklist at startup (not installation, but on job site..).  I'll add this to the repository but thought I'd pass it by you for feedback. ..Doug From: photoboothbiz notifications@github.com To: pgmrgeek/PhotoboothMgr PhotoboothMgr@noreply.github.com Cc: Doug Cody clikphoto@yahoo.com; State change state_change@noreply.github.com Sent: Monday, August 8, 2016 11:03 AM Subject: Re: [pgmrgeek/PhotoboothMgr] Can you please explain to me how this program works with end user? (#1) cool this was the last link in the puzzle to make it a full fledged program, great job. I will check it out soon. On July 26, 2016 at 8:11 PM Doug Cody notifications@github.com wrote:Hi Elliott,Check out version 13.xx. This is the first version to support DigiCamControl for triggering cameras. There is a new button, the "Guest UI" button that opens a dialog with one button - "Click to start". Resize this button over the whole screen so the user has one option, to start the sequence. There's a little nearly hidden button at the bottom right to minimize this dialog to see the rest of the program and photoshop.Let me know if you need assistance getting this up and running...Doug—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. —

**Comment by photoboothbiz** [comment]
SORRY HAVENT' HAD A CHANCE TO TEST IT. WILL DEFFINETELY TRY WHEN THINGS SLOW DOWNOn October 15, 2016 at 2:00 PM Doug Cody notifications@github.com wrote:Howdy, any luck with getting it running? ..Doug  From: photoboothbiz notifications@github.com To: pgmrgeek/PhotoboothMgr PhotoboothMgr@noreply.github.com  Cc: Doug Cody clikphoto@yahoo.com; State change state_change@noreply.github.com Sent: Monday, August 15, 2016 5:09 AM Subject: Re: [pgmrgeek/PhotoboothMgr] Can you please explain to me how this program works with end user? (#1)    SORRY BEEN SWAMPED, REALLY AM INTERESTED THOUGH, YOU ARE VERY VERY GENEROUS WITH YOUR SHARING OF SOFTARE!On August 14, 2016 at 5:26 PM Doug Cody notifications@github.com wrote:Howdy, Any luck getting the software to run?  Attached is a spreadsheet which is a checklist at startup (not installation, but on job site..).  I'll add this to the repository but thought I'd pass it by you for feedback. ..Doug From: photoboothbiz notifications@github.com To: pgmrgeek/PhotoboothMgr PhotoboothMgr@noreply.github.com Cc: Doug Cody clikphoto@yahoo.com; State change state_change@noreply.github.com Sent: Monday, August 8, 2016 11:03 AM Subject: Re: [pgmrgeek/PhotoboothMgr] Can you please explain to me how this program works with end user? (#1) cool this was the last link in the puzzle to make it a full fledged program, great job. I will check it out soon. On July 26, 2016 at 8:11 PM Doug Cody notifications@github.com wrote:Hi Elliott,Check out version 13.xx. This is the first version to support DigiCamControl for triggering cameras. There is a new button, the "Guest UI" button that opens a dialog with one button - "Click to start". Resize this button over the whole screen so the user has one option, to start the sequence. There's a little nearly hidden button at the bottom right to minimize this dialog to see the rest of the program and photoshop.Let me know if you need assistance getting this up and running...Doug—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
